### PR TITLE
Minor edits for the SVD blogpost

### PR DESCRIPTION
**Pull request by jakirkham**
Includes some minor changes to the draft SVD blogpost. Might be easiest to review by commit if the specific diffs are of interest (due to text wrapping).

cc @pentschev @mrocklin

### CODE REVIEW

**Comment by pentschev** [comment]
LGTM.

@jakirkham would you mind adding the BLAS information in your PR here? The NumPy benchmarks use OpenBLAS. Otherwise, let's merge this and I'll edit later to add this info.

**Comment by jakirkham** [comment]
Sure. Which versions of OpenBLAS and cuBLAS were used?

**Comment by pentschev** [comment]
Nevermind, I was using libblas, the output of `numpy.show_config()` doesn't seem accurate. Only realized it when I looked for the openblas package that was not installed. Now I'm using openblas 0.2.18 and cublas 9.2.174. Could you update the links to the graphs too?

1. Fitting: https://gist.githubusercontent.com/pentschev/86445c9c89c3b956f2289d0e9e0c9953/raw/2d4379c74fd210156cf8f99e0ddf70e959e74f61/fitting.png
2: Prediction: https://gist.githubusercontent.com/pentschev/86445c9c89c3b956f2289d0e9e0c9953/raw/2d4379c74fd210156cf8f99e0ddf70e959e74f61/prediction.png

Since I'm only talking about orders of magnitude, there is no need to update any text, it remains correct.

**Comment by pentschev** [comment]
Results with openblas are slightly better, but not enough to change the contents of the post.

**Comment by jakirkham** [comment]
Sorry, one other question, what is the version of cuSOLVER? Is it the same as cuBLAS?

**Comment by pentschev** [comment]
No, cusolver version 9.2.148. If I recall correctly, there was a new release of some libraries for CUDA 9.2, that's why they differ.

**Comment by pentschev** [comment]
LGTM. Thanks for the (post) review, @jakirkham.

**Comment by jakirkham** [comment]
Thanks @pentschev.

@mrocklin, would you have a chance to look as well?

**Comment by pentschev** [comment]
I thought we couldn't host images here, I didn't see any post that wasn't hosting images elsewhere, but that certainly is much better!

**Comment by jakirkham** [comment]
No worries. I wasn't sure initially either, but it seems to work ok.

**Pull request merged**
