### PR TITLE
Only build past posts

### PR DESCRIPTION
**Pull request by jacobtomlinson**
I **think** this should only build past posts. 

https://github.com/jekyll/jekyll/issues/6536

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
cc @jsignell

**Review by jsignell — APPROVED** [review]
Should we just merge and see?

**Comment by jacobtomlinson** [comment]
Yeah. I'm not sure whether your post will be removed though. It depends whether they clear out the files or just build over the top.

**Comment by jsignell** [comment]
looks like it's gone :tada: !

**Pull request merged**
