### PR TITLE
Add note on the new cron job to rebuild the blog nightly

### PR DESCRIPTION
**Pull request by jacobtomlinson**
@jsignell suggested adding a section to the README to describe the changes in #69

### CODE REVIEW

**Review by jsignell — APPROVED** [review]
Horray! What happens when people want to make edits to old posts?

**Comment by jacobtomlinson** [comment]
> What happens when people want to make edits to old posts?

Builds will still be run on merge.

**Comment by jsignell** [comment]
I guess I could have figured that out since #63 built :smile:

**Review by jsignell — APPROVED** [review]
LGTM

**Pull request merged**
