### PR TITLE
Add link to "High level performance of Pandas, Dask, Spark, and Arrow"

### PR DESCRIPTION
**Pull request by scharlottej13**
@jacobtomlinson @mrocklin I was wondering if it would be OK to add a link to a recent Steppingblocks interview with Coiled on their switch from Spark to Dask to your blog post. I started it at "Why we switched from Spark to Dask" since that section of the video seems most relevant. Full video [here](https://youtu.be/jR0Y7NqKJs8).

This is tangentially related to https://github.com/dask/community/issues/259.

cc @adireske

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
I totally agree that it makes sense to add a link here to a video about folks switching from Spark to Dask. And the Steppingblocks video seems great. I'm generally in favour of connecting the two pieces of content.

It does feel a little strange to retroactively add links within the Dask blog to Coiled properties like this though. Especially when the blog post has a `This work is supported by Anaconda Inc` notice at the top. Updating old content feels a bit different compared to new content that is created by folks at Coiled like we are discussing in https://github.com/dask/community/issues/259.

I wonder if one way we could do this without it feeling like a Coiled marketing push would be to snip the three minutes from the YouTube video and put it on the Dask YouTube channel as a separate video. That short video could then call out to the Coiled video for folks to go and watch the rest of the interview. Then we link from the blog to the Dask channel video instead.

Adding that extra hop might help folks switch mindset more cleanly between "This is Dask content sponsored by Anaconda" > "This is Dask content sponsored by Coiled" > "This is Coiled content about Dask".

**Comment by scharlottej13** [comment]
Thanks @jacobtomlinson for taking the time to clearly explain this. I also read through [your comment](https://github.com/dask/community/issues/259#issuecomment-1167263925) on https://github.com/dask/community/issues/259 which adds some nice context.

I updated the PR to link instead to a clip of the Steppingblocks interview on the Dask youtube channel on the [Dask Use Cases playlist](https://youtube.com/playlist?list=PLJ0vO2F_f6OAE1xiEUE7DwMFWbdLCbN3P). I think this adds the extra hop you mentioned, but looking forward to hearing your thoughts. We can also edit an even shorter clip, as you mentioned above.

**Review by jacobtomlinson — APPROVED** [review]
Apologies for the delay in coming back here. That's exactly the kind of hop I had intended. thanks for humouring me here.

**Comment by scharlottej13** [comment]
> Apologies for the delay in coming back here. That's exactly the kind of hop I had intended. thanks for humouring me here.

No problem! I think the extra hop makes a lot of sense

**Pull request merged**
