### PR TITLE
2021 Dask user survey results

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
This PR adds the Dask survey results and report from 2021.

A nicely rendered preview can be seen here: https://github.com/GenevieveBuckley/dask-examples/blob/survey2021/surveys/2021.ipynb

Cross reference: https://github.com/dask/dask-examples/pull/193

### CODE REVIEW

**Comment by mrocklin** [comment]
> In the last year, there has been an increase in the number of people who say that many people throughout their institution use Dask (32 people said this in 2021, compared to 19 in 2020).

Thoughts on trying to convey this visually?  This seems  like it might tell a nice story.

**Comment by GenevieveBuckley** [comment]
> > In the last year, there has been an increase in the number of people who say that many people throughout their institution use Dask (32 people said this in 2021, compared to 19 in 2020).
> 
> Thoughts on trying to convey this visually? This seems like it might tell a nice story.

Sure, that shouldn't be too hard to arrange. 
(FYI I'm busy today & this weekend with PyConAU, so if I don't manage to do squeeze this into a gap somehow, I plan to do it Monday.)

**Comment by mrocklin** [comment]
Have fun!

**Comment by GenevieveBuckley** [comment]
To avoid duplication & confusion, all conversation related to this blogpost is happening over in https://github.com/dask/dask-examples/pull/193

**Comment by GenevieveBuckley** [comment]
Blogpost is up! https://blog.dask.org/2021/09/15/user-survey

The link to the binder won't work until [PR 193 at dask-examples is merged](https://github.com/dask/dask-examples/pull/193#issuecomment-920701722). I've scheduled a tweet to promote the blogpost tomorrow, when someone will have had a chance to merge that PR.

**Pull request merged**
