### PR TITLE
Recap of the life science workshop at the Dask Summit 2021

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
Blogpost recapping the life science workshop at the Dask Summit. This is primarily intended as an overview for people who weren't able to attend this time round.

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
@jakirkham let me know if you feel like there's anything important that should also be added

**Comment by jakirkham** [comment]
I think there were a couple more people on the last day that were not on the list here, but don't recall bios atm

**Comment by jakirkham** [comment]
Also not sure if we want to summarize what was discussed

**Comment by GenevieveBuckley** [comment]
Yeah, there were definitely more people attending than we have short bios for (I did try and note that). Perhaps we should have a quick sync up about what was discussed. It did get hard to keep track especially when people split out into breakout rooms.

**Pull request merged**
