### PR TITLE
Add SciPy 2020 video

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Just spotted the video is up. Adding it to the blog post.

### CODE REVIEW

**Review by jrbourbeau — APPROVED** [review]
Thanks @jacobtomlinson!

**Comment by mrocklin** [comment]
@jacobtomlinson do you want to tweet out the video as well?

**Comment by jacobtomlinson** [comment]
Sounds good. I'm away from my computer right now. Would you mind doing it?

**Comment by mrocklin** [comment]
Done.  It will go out tomorrow.

**Pull request merged**
