### PR TITLE
Cross-post queueing blog post

### PR DESCRIPTION
**Pull request by scharlottej13**
cross-post @gjoseph92's queueing blog post with canonical link to coiled blog, see https://github.com/dask/community/issues/291#issuecomment-1317737195

also updated `_config.yml` per a deprecation warning.

@gjoseph92 I copied this from github.com/coiled/blog-drafts. I noticed some differences between this version + https://www.coiled.io/blog/reducing-dask-memory-usage and tried to update accordingly, but I may have missed something. Also had some trouble adding in your figure captions (for some reason using the figcaption html wasn't rendering) so I used some italics and section lines instead.

cc @mrocklin @jacobtomlinson @jrbourbeau

### CODE REVIEW

**Review by jacobtomlinson — APPROVED** [review]
This looks great thanks for syndicating this over here! It looks good to me, especially the new canonical link support. 

I'll wait for @gjoseph92 to give a 👍 before merging.

**Comment by scharlottej13** [comment]
Sounds good, thanks @jacobtomlinson for the review!

**Comment by mrocklin** [comment]
I think that Gabe is out on vacation this week.  I suggest that we give him
a day to respond and, if he doesn't move on assuming his consent (I think
that he wrote this markdown file anyway)

**Comment by scharlottej13** [comment]
> (I think that he wrote this markdown file anyway)

Yup, I copied over the file Gabe wrote from coiled/blog-drafts. I made some formatting-related changes and changed the title to match the published blogpost, but otherwise did not edit any written content.

**Review by jrbourbeau — APPROVED** [review]
> Yup, I copied over the file Gabe wrote from coiled/blog-drafts. I made some formatting-related changes and changed the title to match the published blogpost, but otherwise did not edit any written content.

Given this, I'm going to go ahead and merge this in

EDIT: We can definitely still make changes based on any feedback @gjoseph92 might have. But given he was the one who originally authored the content here, I think it's okay to proceed

**Pull request merged**
